version: "3.3"
services:
    sqldata:
        container_name: sql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        build:
            dockerfile: Dockerfile
        environment:
          - SA_PASSWORD=Trommelhelden24!
          - ACCEPT_EULA=Y
        ports:
          - "1433:1433"
        networks:
          - my_network

    react:
        build: ../../development/app/client
        container_name: client_react
        stdin_open: true
        tty: true
        environment:
          NODE_PATH: src
        ports:
          - 3000:3000  
        networks:
          - my_network  
    node:
        build: ../../development/app/server
        container_name: node
        environment:
          DATABASE_HOST: sql-server
        depends_on:
          - react
          - sqldata
        ports:
          - 5000:5000
        networks:
          - my_network
        healthcheck:
          test: ["CMD", "powershell", "-command", "Test-SqlConnection", "-ServerName", "sqldata", "-DatabaseName", "master", "-ConnectionTimeout", "10"]
          interval: 30s
          timeout: 10s
          retries: 5

networks:
  my_network: