version: "3.3"
services:
    sqldata:
        container_name: sql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        build:
            dockerfile: Dockerfile
        environment:
          - SA_PASSWORD=Trommelhelden24!
          - ACCEPT_EULA=Y
        ports:
          - "1433:1433"