version: "3.3"
services:
    sqldata:
        container_name: sql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        build:
            dockerfile: Dockerfile
        environment:
          - SA_PASSWORD=Trommelhelden24!
          - ACCEPT_EULA=Y
        ports:
          - "1433:1433"
    react:
        build: ../../development/app/client
        container_name: client_react
        stdin_open: true
        tty: true
        environment:
          NODE_PATH: src
        ports:
          - 3000:3000