=== Arbeit im Team
[cols="1, 3, 4"]
|===
| Alias | Teammitglied | Fachsemester/Studiengang

| Di | Quang Duy Pham | 5. Sem. Allgemeine Informatik
| Beni | Thanh Binh Nguyen | 7. Sem. Allgemeine Informatik
| Sabine | Sabine Adam | 7. Sem. Allgemeine Informatik
| Vitali | Vitali Tichonow | 5. Sem. Allgemeine Informatik
|===

==== Rollen
Eine klassische Rollenverteilung fand innerhalb des Projektseminars nicht konkret statt. Allerdings haben sich nach den ersten Wochen Mitglieder der Gruppe durch ihre Taten augenscheinlich selbst in die jeweiligen Rollen versetzt, welche nachträglich wie folgt identifiziert werden können:

Für die erste Aufgabe, die grobe Analyse und Erstellung der Wireframes, habt sich das ganze Team zusammengefunden, sodass diese Rolle keiner einzelnen Person zugeschrieben werden kann.

Sabine fand sich nach kurzer Zeit in der Rolle des Managements wieder. Regelmäßig motivierte sie das Team, koordinierte zusätzliche Treffen für ein gemeinsames Arbeiten und übernahm hauptsächlich das Reden während der wöchentlichen Meetings um den Stand des Projektes darzulegen.

Da Di schon Erfahrungen im Umgang mit dem gewählten Framework hatte, war er der inoffizielle Hauptentwickler der Gruppe. Natürlich war jedes einzelne Mitglied an der Programmierung selbst beteiligt, doch Di war der erste Ansprechpartner, wenn es zu Fragen zu beispielsweise hartnäckigen fehlermeldungen kam.

Die Rolle des Testers wurde ebenfalls jedem zu Teil. Nachdem eine neue Funktion implementiert und auf Github geladen wurde, wurde das Team meist direkt nachrichtlich verständigt und so zum ausgiebigen Testen aufgefordert. 

=== Werkzeuge
==== Kommunikation
Gleich zu Beginn des Projektes wurde ein Discord Server aufgesetzt, der wöchentlich für virtuelle Treffen genutzt werden sollte. Durch die Einrichtung verschiedener Kanäle auf die gezielt nur bestimmte Personen Zugriff hatten, konnte zwischen offiziellen Meetings zusammen mit Herrn Professor Thiele und Team-Meetings unterschieden werden.

Des Weiteren wurde am Anfang der Gruppenarbeit eine WhatsApp-Gruppe eingerichtet, in der zumeist Termine für zusätzliche Meetings ausgemacht wurden. Kleinere Probleme oder Fragen konnten so textuell schnell geklärt werden.

==== Dokumentation
[cols="3, 5"]
|===
| Tool                  | Verwendungszweck

| git/ Github           | Versionsverwaltung des gesamten Projektes
| Asciidoc              | Verfassung schriftlicher Dokumentationen
Codedokumentation
| Diagrams.net          |Erstellung von Diagrammen und Wireframes
|===

==== Framework

Obwohl das Team am Anfang des Projektes nach Beratung für das in Python-geschriebene Webframework Flask entschieden hatte, wurde nach kurzer Zeit beschlossen, auf React umzusteigen. Diese Entscheidung wurde getroffen, da ein Gruppenmitglied bereits über grundlegende Kenntnisse in React verfügte. Der Umstieg ermöglichte es dem Team, die Entwicklungszeit zu beschleunigen.

React ist kein Framework, sondern eine JavaScript-Bibliothek für die Erstellung von Benutzeroberflächen (UI). Es ermöglicht, einzelne UI-Komponenten zu erstellen, die unabhängig voneinander verwendet werden können und sich automatisch aktualisieren, wenn sich die Daten ändern. 

Außerdem ist React eine der am weitesten verbreiteten JavaScript-Bibliotheken. Das Erlangen der Kenntnisse darin kann die Chancen im späteren Berufsleben erhöhen, wenn man sich für eine Karriere in der Webentwicklung entscheidet.

==== Deployment
ToDo

=== Entwicklungsprozess und zeitlicher Ablauf
Schon zu Begin des Projektes war der grobe Umfang der Programmierarbeit bekannt, da Funktionalitäten wie das Neuanlegen, Bearbeiten und Löschen zu den Mindestanforderungen gehörten. Nach einer ersten Analyse und Erstellung von Use-Cases sowie den dazugehörigen Wireframes konnte mit dem eigentlichen Entwicklungsprozess begonnen werden. +
Mittels einer iterative Entwicklung konnte ein regelmäßiger Fortschritt erzielt werden, der in den wöchentlichen Meetings präsentiert und diskutiert werden konnte. Nach der Fertigstellung der Kunden-, Mitarbeiter- und Ersatzteilseite konnte der Auftrags-Tab weiter ausgebaut werden, welcher bei der Erstellung eines Auftrages die Möglichkeit bieten sollte, einen Trigger in die ID-Erzeugung mit einzubeziehen statt diese manuell zu vergeben. Das letzte Inkrement der Applikation bildete die Seite "Bericht", welche nach Eingabe einer natürlichen Zahl, Ersatzteile listet, welche mindestens so oft verwendet wurden, wie angegeben.


=== Probleme und Lösungen

* *Probleme mit JSON* +
ToDo