=== Arbeit im Team
[cols="1, 3, 4"]
|===
| Alias | Teammitglied | Fachsemester/Studiengang

| Di | Quang Duy Pham | 5. Sem. Allgemeine Informatik
| Beni | Thanh Binh Nguyen | 7. Sem. Allgemeine Informatik
| Sabine | Sabine Adam | 7. Sem. Allgemeine Informatik
| Vitali | Vitali Tichonow | 5. Sem. Allgemeine Informatik
|===

==== Rollen
Eine klassische Rollenverteilung fand innerhalb des Projektseminars nicht konkret statt. Allerdings haben sich nach den ersten Wochen Mitglieder der Gruppe durch ihre Taten augenscheinlich selbst in die jeweiligen Rollen versetzt, welche nachträglich wie folgt identifiziert werden können:

Für die erste Aufgabe, die grobe Analyse und Erstellung der Wireframes, habt sich das ganze Team zusammengefunden, sodass diese Rolle keiner einzelnen Person zugeschrieben werden kann.

Sabine fand sich nach kurzer Zeit in der Rolle des Managements wieder. Regelmäßig motivierte sie das Team, koordinierte zusätzliche Treffen für ein gemeinsames Arbeiten und übernahm hauptsächlich das Reden während der wöchentlichen Meetings um den Stand des Projektes darzulegen.

Da Di schon Erfahrungen im Umgang mit dem gewählten Framework hatte, war er der inoffizielle Hauptentwickler der Gruppe. Natürlich war jedes einzelne Mitglied an der Programmierung selbst beteiligt, doch Di war der erste Ansprechpartner, wenn es zu Fragen zu beispielsweise hartnäckigen ehlermeldungen kam.

Die Rolle des Testers wurde ebenfalls jedem zu Teil. Nachdem eine neue Funktion implementiert und auf Github geladen wurde, wurde das Team meist direkt nachrichtlich verständigt und so zum ausgiebigen Testen aufgefordert. 

=== Werkzeuge
==== Kommunikation
Gleich zu Beginn des Projektes wurde ein Discord Server aufgesetzt, der wöchentlich für virtuelle Treffen genutzt werden sollte. Durch die Einrichtung verschiedener Kanäle auf die gezielt nur bestimmte Personen Zugriff hatten, konnte zwischen offiziellen Meetings zusammen mit Herrn Professor Thiele und Team-Meetings unterschieden werden.

Des Weiteren wurde am Anfang der Gruppenarbeit eine WhatsApp-Gruppe eingerichtet, in der zumeist Termine für zusätzliche Meetings ausgemacht wurden. Kleinere Probleme oder Fragen konnten so textuell schnell geklärt werden.

==== Dokumentation
[cols="3, 5"]
|===
| Tool                  | Verwendungszweck

| git/ Github           | Versionsverwaltung des gesamten Projektes
| Asciidoc              | Verfassung schriftlicher Dokumentationen
Codedokumentation
| Diagrams.net          |Erstellung von Diagrammen und Wireframes
|===

==== Framework

Obwohl das Team am Anfang des Projektes nach Beratung für das in Python-geschriebene Webframework Flask entschieden hatte, wurde nach kurzer Zeit beschlossen, auf React umzusteigen. Diese Entscheidung wurde getroffen, da ein Gruppenmitglied bereits über grundlegende Kenntnisse in React verfügte. Der Umstieg ermöglichte es dem Team, die Entwicklungszeit zu beschleunigen.

React ist kein Framework, sondern eine JavaScript-Bibliothek für die Erstellung von Benutzeroberflächen (UI). Es ermöglicht, einzelne UI-Komponenten zu erstellen, die unabhängig voneinander verwendet werden können und sich automatisch aktualisieren, wenn sich die Daten ändern. 

Außerdem ist React eine der am weitesten verbreiteten JavaScript-Bibliotheken. Das Erlangen der Kenntnisse darin kann die Chancen im späteren Berufsleben erhöhen, wenn man sich für eine Karriere in der Webentwicklung entscheidet.

==== Deployment
Um nach Fertigstellung der Software diese auch anderen Studierenden zur Verfügung stellen zu können, haben wir uns dazu entschieden die Applikation mit Hilfe von Docker auszuliefern. +
Mittels Docker können Anwendungen schneller bereitgestellt werden. Die Applikation kann hierbei in einen oder mehreren isolierten "Containern" ausgeführt werden, wodurch eine (zeit-) aufwendige Installation benötigter Module vermieden werden kann. +

Unser Projekt gliedert sich in drei verschiedene Container: +
Einer beinhaltet den MS SQL Server mit samt dem Datenbestand der Trommelheldendatenbank, einer den Client der App und einer den Server.

*Systemvoraussetzungen*

*Mindestanforderungen an Hardware*

* Ein internetfähiges Gerät (Smartphone, Tablet, PC) für die Nutzung der Anwendung

* PC/Server mit Docker und Git

* Für Docker: link:https://docs.docker.com/desktop/windows/install/[Windows], link:https://docs.docker.com/desktop/linux/install/[Linux], link:https://docs.docker.com/desktop/mac/install/[Mac]

* Microsoft SQL Server weist Kompatibilitätsprobleme unter Mac mit Apple-Chip auf

*Softwareanforderungen*

* Aktueller Webbrowser (Chrome Ver. 109.0.5414.119 oder höher, Safari Ver. 16.1 oder höher) mit HTML5- und Javascript Unterstützung
* Docker Compose Ver. 3.3 oder höher

*Systemeinrichtung*

Die Software ist eine webbasierte Anwendung, die sich in einem privaten Repository auf GitHub befindet (link:https://github.com/EliSa-GH/ps-trommelhelden[Link]). Die Anwendung besteht aus mehreren Ordnern, Frontend- und Backend-Komponenten.

Bevor mit der Installation fortgefahren wird, ist es empfehlenswert, einen Fork vom Repository zu erzeugen und im eigenen Account abzuspeichern. 

Im Terminal:

`$ git fork https://github.com/EliSa-GH/ps-trommelhelden.git`

Um die Anwendung von GitHub auf Ihren eigenen PC/Server zu speichern, muss diese zuerst von GitHub geladen werden.

`$ git clone https://github.com/EliSa-GH/ps-trommelhelden.git`

Die Anwendung besteht aus zwei Backend-Komponenten: Webserver(Node.js Ver. 19.1) und MSSQL (SQL Server 2019) und einer Frontend-Konponente (React Ver. 11.10.5) die in einem Docker-Container gespeichert sind.

Um die Software zu installieren, soll ein Docker Container ausgeführt werden. Dafür gibt es zwei Möglichkeiten:

* Im Ordner "sql-server" unter "deployment" die Datei "docker-compose.yml" per Drag and Drop in den Docker Desktop schieben und anschließend auf "Start" drücken. -> Diese Vorgehensweise funktioniert nur unter Windows/Mac

* Im Terminal den Ordner "sql-server" unter "deployment" wählen und im Anschluss mit dem Befehl "docker-compose up" die Software ausführen (Docker muss gestartet sein):


1. Zum Ordner navigieren:

 $ cd pfad/zum/Ordner/ps-trommelhelden

2. In Unterordner wechseln:

 $ cd deployment/sql-server/

3. Server starten:

 ** Für neuere Docker Versionen:

 $ docker compose up

 ** Für ältere Docker Versionen:

 $ docker-compose up

Die Anwendung ist out of the box einsatzbereit, das bedeutet es müssen keine weiteren Konfigurationen vorgenommen werden. 

Um zu überprüfen, ob die Anwendung funktioniert, soll im Webbrowser in der Adresszeile "localhost:3000" eingegeben werden. Daraufhin wird die Webseite geöffnet.

*Fehlerbehebung*

Die meisten Fehler, die auftreten können, werden mit Docker zusammenhängen. 

Die typischen Fehler und deren Behebung finden Sie unter folgendem Link:

* link:https://docs.docker.com/desktop/windows/troubleshoot/[Docker Troubleshoot]

*Weitere Dokumentationen*

* link:https://docs.docker.com/desktop/[Docker]
* link:https://reactjs.org/docs/getting-started.html[React]
* link:https://nodejs.org/en/docs/[Node.js]
* link:https://learn.microsoft.com/en-us/sql/?view=sql-server-ver16[Microsoft SQL]

=== Entwicklungsprozess und zeitlicher Ablauf
Schon zu Begin des Projektes war der grobe Umfang der Programmierarbeit bekannt, da Funktionalitäten wie das Neuanlegen, Bearbeiten und Löschen zu den Mindestanforderungen gehörten. Nach einer ersten Analyse und Erstellung von Use-Cases sowie den dazugehörigen Wireframes konnte mit dem eigentlichen Entwicklungsprozess begonnen werden. +
Mittels einer iterative Entwicklung konnte ein regelmäßiger Fortschritt erzielt werden, der in den wöchentlichen Meetings präsentiert und diskutiert werden konnte. Nach der Fertigstellung der Kunden-, Mitarbeiter- und Ersatzteilseite konnte der Auftrags-Tab weiter ausgebaut werden, welcher bei der Erstellung eines Auftrages die Möglichkeit bieten sollte, einen Trigger in die ID-Erzeugung mit einzubeziehen statt diese manuell zu vergeben. Das letzte Inkrement der Applikation bildete die Seite "Bericht", welche nach Eingabe einer natürlichen Zahl, Ersatzteile listet, welche mindestens so oft verwendet wurden, wie angegeben.


=== Probleme und Lösungen

*Probleme mit JSON:* Am Anfang des Projekts entschied das Team, Python Flask zur Verwaltung von API-Anfragen aus der Frontend-Anwendung und SQLAlchemy als Werkzeug zum Abrufen von Daten aus dem SQL Server zu verwenden. Während des Projekts stellten sie jedoch fest, dass die Verwendung von Python-Dictionaries durch SQLAlchemy zur Speicherung von Daten für das Projekt ungeeignet war, da eine Serialisierung der Dictionary-Daten in JSON-Format erforderlich war. Darüber hinaus gab es Probleme bei der Serialisierung von Decimal- und Datetime-Typen. Daher entschied das Team, zu einer vertrauteren Sprache für die Backend-Entwicklung zu wechseln, JavaScript. Sie untersuchten mehrere Backend-Frameworks und wählten schließlich Express aus, um die Backend-Seite zu handhaben. Nach dem Wechsel stellten sie keine strukturellen Probleme fest. 